# Generated by Django 5.1.15 on 2026-06-17 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        ('competitions', '0005_remove_competitionentry_season_remove_award_season_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='clubs.club', verbose_name='클럽'),
        ),
    ]
