# Generated by Django 5.1.15 on 2026-06-17 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='클럽명')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='URL 슬러그')),
                ('logo', models.ImageField(blank=True, upload_to='clubs/logos/', verbose_name='로고')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '클럽',
                'verbose_name_plural': '클럽',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClubMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', '소유자'), ('STAFF', '운영진')], default='STAFF', max_length=8, verbose_name='역할')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='clubs.club', verbose_name='클럽')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_memberships', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '클럽 멤버십',
                'verbose_name_plural': '클럽 멤버십',
                'ordering': ['club', 'user'],
                'unique_together': {('user', 'club')},
            },
        ),
    ]
