# Generated by Django 5.1.15 on 2026-06-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_player_squad'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='삭제 일시'),
        ),
    ]
