# Generated by Django 5.1.15 on 2026-06-17 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        ('teams', '0005_remove_teammembership_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='clubs.club', verbose_name='클럽'),
        ),
        migrations.AddField(
            model_name='team',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='clubs.club', verbose_name='클럽'),
        ),
        migrations.AlterField(
            model_name='team',
            name='slug',
            field=models.SlugField(max_length=120, verbose_name='URL 슬러그'),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('club', 'slug')},
        ),
    ]
