# Generated by Django 5.1.15 on 2026-06-15 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_opponentmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchevent',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assists', to='matches.matchevent', verbose_name='연결된 득점'),
        ),
    ]
