# Generated by Django 5.1.15 on 2026-06-17 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        ('matches', '0011_match_advance_feeder_match_opponent_feeder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='clubs.club', verbose_name='클럽'),
        ),
        migrations.AddField(
            model_name='opponent',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opponents', to='clubs.club', verbose_name='클럽'),
        ),
        migrations.AddField(
            model_name='opponentmatch',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opponent_matches', to='clubs.club', verbose_name='클럽'),
        ),
        migrations.AlterField(
            model_name='opponent',
            name='name',
            field=models.CharField(max_length=120, verbose_name='팀명'),
        ),
        migrations.AlterUniqueTogether(
            name='opponent',
            unique_together={('club', 'name')},
        ),
    ]
