# Generated by Django 5.1.15 on 2026-06-20 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0015_match_period_match_second_half_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='일시정지 시각'),
        ),
        migrations.AddField(
            model_name='match',
            name='paused_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='누적 정지(초)'),
        ),
    ]
